### ISSUE TITLE
[MUST] TODO LIST

### ISSUE THREAD

**Issue by parktest0325** [NTF-marketplace/scam-factory#2]
### 클라이언트
- [ ] 메타마스크와 상호작용해서 현재 로그인한 계정으로 사용
- [ ] 로그인한 계정의 가스비낼 코인 표시
- [x] NFT 이미지 리스트를 좀더 깔끔하게 표시
- [x] NFT 이미지 리스트 버그 제거 (누적돼서 표시되는 문제 등)
- [ ] 각 작업에 대한 성공 및 실패 에러모달 표시
- [x] 발급할 NFT 수량, 이름, 심볼 유저가 컨트롤 가능하게하기
- [x] 각각의 Part가 trait으로 지정
